stages:
  - deploy

deploy_to_dokku:
  stage: deploy
  tags:
    - hp70602-runner
  before_script:
    # 1. Cài đặt các gói SSH cần thiết
    - apk update && apk add git openssh-client

    # 2. Khởi động trình quản lý mã khóa ssh-agent
    - eval $(ssh-agent -s)

    # 3. Phân quyền trực tiếp cho file Key do GitLab cấp (Bắt buộc phải là 600)
    - chmod 600 "$SSH_PRIVATE_KEY"

    # 4. Nạp trực tiếp file key vào Agent (Không dùng lệnh echo nữa)
    - ssh-add "$SSH_PRIVATE_KEY"

    # 5. Tạo thư mục cấu hình ssh và quét IP nhận diện máy chủ Dokku
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $DELL_SERVER_IP >> ~/.ssh/known_hosts
  script:
    - echo "--- BẮT ĐẦU QUY TRÌNH DEPLOY LÊN DOKKU ---"
    - git remote remove dokku || true
    - git remote add dokku dokku@$DELL_SERVER_IP:podcast-api
    - git push dokku HEAD:refs/heads/master --force
    - echo "--- DEPLOY THÀNH CÔNG! DOKKU ĐANG XỬ LÝ KHỞI CHẠY NGẦM ---"
  only:
    - main
