stages:
  - deploy

deploy_to_dokku:
  stage: deploy
  tags:
    - hp70602-runner
  before_script:
    # ĐÂY LÀ DÒNG BỊ THIẾU: Cài đặt SSH client vào container Alpine trước khi gọi lệnh SSH
    - apk update && apk add git openssh-client

    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $DELL_SERVER_IP >> ~/.ssh/known_hosts
  script:
    - echo "--- BẮT ĐẦU QUY TRÌNH DEPLOY LÊN DOKKU ---"
    - git remote remove dokku || true
    - git remote add dokku dokku@$DELL_SERVER_IP:podcast-api
    - git push dokku HEAD:refs/heads/master --force
    - echo "--- DEPLOY THÀNH CÔNG! DOKKU ĐANG XỬ LÝ KHỞI CHẠY NGẦM ---"
  only:
    - main
